# Generated by Django 3.1.3 on 2021-01-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('idKlienta', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokoje',
            fields=[
                ('numerPokoju', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('liczbaMiejsc', models.IntegerField()),
                ('cenaNetto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('numerRezerwacji', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dataOd', models.DateField()),
                ('dataDo', models.DateField()),
                ('Klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Klienci', to='HotelRoomBooking.klienci')),
                ('numerPokoju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pokoje', to='HotelRoomBooking.pokoje')),
            ],
        ),
        migrations.CreateModel(
            name='Platnosci',
            fields=[
                ('idPlatnosci', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('doZaplaty', models.FloatField()),
                ('email', models.CharField(max_length=100)),
                ('Rezerwacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rezerwacjr', to='HotelRoomBooking.rezerwacje')),
            ],
        ),
    ]
