# Generated by Django 3.1.3 on 2020-11-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('numerRezerwacji', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('numerPokoju', models.IntegerField()),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platnosci',
            fields=[
                ('numerRezerwacji', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('doZaplaty', models.FloatField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokoje',
            fields=[
                ('liczbaMiejsc', models.IntegerField()),
                ('cenaNetto', models.FloatField()),
                ('numerPokoju', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('numerRezerwacji', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dataOd', models.DateTimeField()),
                ('dataDo', models.DateTimeField()),
                ('numerPokoju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelRoomBooking.pokoje')),
            ],
        ),
    ]
