# Generated by Django 3.1.3 on 2021-01-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platnosci',
            name='Rezerwacja',
        ),
        migrations.AddField(
            model_name='platnosci',
            name='RezerwacjaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Rezerwacje', to='HotelRoomBooking.rezerwacje'),
            preserve_default=False,
        ),
    ]
