# Generated by Django 3.1.3 on 2021-01-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0003_klienci_rezerwacje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienci',
            name='rezerwacje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rezerwacja', to='HotelRoomBooking.rezerwacje'),
        ),
    ]
