# Generated by Django 3.1.3 on 2021-01-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0004_auto_20210103_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerwacje',
            old_name='Klient',
            new_name='idKlienta',
        ),
        migrations.AlterField(
            model_name='klienci',
            name='rezerwacje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='HotelRoomBooking.rezerwacje'),
        ),
    ]
