# Generated by Django 3.1.3 on 2021-01-03 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0007_auto_20210103_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokoje',
            name='rezerwacje',
        ),
        migrations.RemoveField(
            model_name='rezerwacje',
            name='idKlienta',
        ),
        migrations.AddField(
            model_name='klienci',
            name='rezerwacje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='HotelRoomBooking.rezerwacje'),
            preserve_default=False,
        ),
    ]
