# Generated by Django 3.1.3 on 2021-01-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0008_auto_20210103_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienci',
            name='rezerwacje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved', to='HotelRoomBooking.rezerwacje'),
        ),
    ]
