# Generated by Django 3.1.3 on 2021-01-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0009_auto_20210103_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platnosci',
            name='RezerwacjaId',
        ),
        migrations.AddField(
            model_name='pokoje',
            name='zarezerwowany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zarezerwowany', to='HotelRoomBooking.rezerwacje'),
            preserve_default=False,
        ),
    ]
