# Generated by Django 3.1.3 on 2021-01-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0010_auto_20210103_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokoje',
            name='zarezerwowany',
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='numerPokoju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zarezerwowany', to='HotelRoomBooking.pokoje'),
        ),
    ]
