# Generated by Django 3.1.3 on 2021-01-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRoomBooking', '0011_auto_20210103_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klienci',
            name='rezerwacje',
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='numerKlienta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='HotelRoomBooking.klienci'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='numerPokoju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='HotelRoomBooking.pokoje'),
        ),
    ]
