# Generated by Django 3.1.3 on 2021-01-21 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelRoomBooking', '0016_auto_20210121_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoje',
            name='wlasciciel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PokojeOwn', to='auth.user'),
            preserve_default=False,
        ),
    ]
